name: Build Devlogs Website

on:
  push:
    paths:
      - "devlogs/**"
      - ".github/workflows"
  pull_request:
    paths:
      - "devlogs/**"
      - ".github/workflows"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    if: ${{ github.repository == "Open-IA/Open.Quartz" }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Make a Directory for Quartz Project
        run: |
          mkdir -p original-quartz
          cd original-quartz
          git clone https://github.com/jackyzha0/quartz
          cp ../devlogs ./ -r
          cp ../quartz.config.ts ./
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build -d devlogs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}/quartz
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4